apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: frontend
        update-version: "24"
    spec:
      containers:
        - name: frontend
          image: registry.digitalocean.com/remah/be:v22
          resources:
            requests:
              cpu: 50m
          ports:
          - containerPort: 4000
            name: "4000-port"
          envFrom:
          - configMapRef: 
              name: front-store-env
