name: Build and publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  Send_Slack:
    name: Send To Slack
    runs-on: ubuntu-latest
    steps:
      - id: slack
        name: Send to Slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: 'C04DKA10V24'
          payload: |
            {
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "plain_text",
                   "text": "A new Release has just Deployed ::rocket::rocket::rocket::rocket::rocket::rocket:",
                   "emoji": true
                 }
               },
               {
                 "type": "section",
                 "text": {
                   "type": "plain_text",
                   "text": "Our Domain is : https://abdalah.remah.world",
                   "emoji": true
                 }
               },
               {
                 "type": "image",
                 "image_url": "https://www.pngall.com/wp-content/uploads/2016/04/Hosting-PNG-Images.png",
                 "alt_text": "inspiration"
               }
             ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
